---
# all non secret vars
hdd: {
  poolName: DockerPool,
}

adminuser: user # should be an existing one from above

docker: {
  external_network: net_proxy,
  data_dir: '/{{hdd.poolName}}/docker/data',
  # data for docker env
  PUID: '1000',
  PGID: '115'
}
